<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ["name"=>"Afghanistan","code"=>"AF","mobile_code"=>"+93"],
            ["name"=>"Albania","code"=>"AL","mobile_code"=>"+355"],
            ["name"=>"Algeria","code"=>"DZ","mobile_code"=>"+213"],
            ["name"=>"Andorra","code"=>"AD","mobile_code"=>"+376"],
            ["name"=>"Angola","code"=>"AO","mobile_code"=>"+244"],
            ["name"=>"Antigua and Barbuda","code"=>"AG","mobile_code"=>"+1-268"],
            ["name"=>"Argentina","code"=>"AR","mobile_code"=>"+54"],
            ["name"=>"Armenia","code"=>"AM","mobile_code"=>"+374"],
            ["name"=>"Australia","code"=>"AU","mobile_code"=>"+61"],
            ["name"=>"Austria","code"=>"AT","mobile_code"=>"+43"],
            ["name"=>"Azerbaijan","code"=>"AZ","mobile_code"=>"+994"],
            ["name"=>"Bahamas","code"=>"BS","mobile_code"=>"+1-242"],
            ["name"=>"Bahrain","code"=>"BH","mobile_code"=>"+973"],
            ["name"=>"Bangladesh","code"=>"BD","mobile_code"=>"+880"],
            ["name"=>"Barbados","code"=>"BB","mobile_code"=>"+1-246"],
            ["name"=>"Belarus","code"=>"BY","mobile_code"=>"+375"],
            ["name"=>"Belgium","code"=>"BE","mobile_code"=>"+32"],
            ["name"=>"Belize","code"=>"BZ","mobile_code"=>"+501"],
            ["name"=>"Benin","code"=>"BJ","mobile_code"=>"+229"],
            ["name"=>"Bhutan","code"=>"BT","mobile_code"=>"+975"],
            ["name"=>"Bolivia","code"=>"BO","mobile_code"=>"+591"],
            ["name"=>"Bosnia and Herzegovina","code"=>"BA","mobile_code"=>"+387"],
            ["name"=>"Botswana","code"=>"BW","mobile_code"=>"+267"],
            ["name"=>"Brazil","code"=>"BR","mobile_code"=>"+55"],
            ["name"=>"Brunei Darussalam","code"=>"BN","mobile_code"=>"+673"],
            ["name"=>"Bulgaria","code"=>"BG","mobile_code"=>"+359"],
            ["name"=>"Burkina Faso","code"=>"BF","mobile_code"=>"+226"],
            ["name"=>"Burundi","code"=>"BI","mobile_code"=>"+257"],
            ["name"=>"Cabo Verde","code"=>"CV","mobile_code"=>"+238"],
            ["name"=>"Cambodia","code"=>"KH","mobile_code"=>"+855"],
            ["name"=>"Cameroon","code"=>"CM","mobile_code"=>"+237"],
            ["name"=>"Canada","code"=>"CA","mobile_code"=>"+1"],
            ["name"=>"Central African Republic","code"=>"CF","mobile_code"=>"+236"],
            ["name"=>"Chad","code"=>"TD","mobile_code"=>"+235"],
            ["name"=>"Chile","code"=>"CL","mobile_code"=>"+56"],
            ["name"=>"China","code"=>"CN","mobile_code"=>"+86"],
            ["name"=>"Colombia","code"=>"CO","mobile_code"=>"+57"],
            ["name"=>"Comoros","code"=>"KM","mobile_code"=>"+269"],
            ["name"=>"Congo (Congo-Brazzaville)","code"=>"CG","mobile_code"=>"+242"],
            ["name"=>"Congo (Democratic Republic)","code"=>"CD","mobile_code"=>"+243"],
            ["name"=>"Costa Rica","code"=>"CR","mobile_code"=>"+506"],
            ["name"=>"Croatia","code"=>"HR","mobile_code"=>"+385"],
            ["name"=>"Cuba","code"=>"CU","mobile_code"=>"+53"],
            ["name"=>"Cyprus","code"=>"CY","mobile_code"=>"+357"],
            ["name"=>"Czech Republic","code"=>"CZ","mobile_code"=>"+420"],
            ["name"=>"Denmark","code"=>"DK","mobile_code"=>"+45"],
            ["name"=>"Djibouti","code"=>"DJ","mobile_code"=>"+253"],
            ["name"=>"Dominica","code"=>"DM","mobile_code"=>"+1-767"],
            ["name"=>"Dominican Republic","code"=>"DO","mobile_code"=>"+1-809"],
            ["name"=>"Ecuador","code"=>"EC","mobile_code"=>"+593"],
            ["name"=>"Egypt","code"=>"EG","mobile_code"=>"+20"],
            ["name"=>"El Salvador","code"=>"SV","mobile_code"=>"+503"],
            ["name"=>"Equatorial Guinea","code"=>"GQ","mobile_code"=>"+240"],
            ["name"=>"Eritrea","code"=>"ER","mobile_code"=>"+291"],
            ["name"=>"Estonia","code"=>"EE","mobile_code"=>"+372"],
            ["name"=>"Eswatini","code"=>"SZ","mobile_code"=>"+268"],
            ["name"=>"Ethiopia","code"=>"ET","mobile_code"=>"+251"],
            ["name"=>"Fiji","code"=>"FJ","mobile_code"=>"+679"],
            ["name"=>"Finland","code"=>"FI","mobile_code"=>"+358"],
            ["name"=>"France","code"=>"FR","mobile_code"=>"+33"],
            ["name"=>"Gabon","code"=>"GA","mobile_code"=>"+241"],
            ["name"=>"Gambia","code"=>"GM","mobile_code"=>"+220"],
            ["name"=>"Georgia","code"=>"GE","mobile_code"=>"+995"],
            ["name"=>"Germany","code"=>"DE","mobile_code"=>"+49"],
            ["name"=>"Ghana","code"=>"GH","mobile_code"=>"+233"],
            ["name"=>"Greece","code"=>"GR","mobile_code"=>"+30"],
            ["name"=>"Grenada","code"=>"GD","mobile_code"=>"+1-473"],
            ["name"=>"Guatemala","code"=>"GT","mobile_code"=>"+502"],
            ["name"=>"Guinea","code"=>"GN","mobile_code"=>"+224"],
            ["name"=>"Guinea-Bissau","code"=>"GW","mobile_code"=>"+245"],
            ["name"=>"Guyana","code"=>"GY","mobile_code"=>"+592"],
            ["name"=>"Haiti","code"=>"HT","mobile_code"=>"+509"],
            ["name"=>"Honduras","code"=>"HN","mobile_code"=>"+504"],
            ["name"=>"Hungary","code"=>"HU","mobile_code"=>"+36"],
            ["name"=>"Iceland","code"=>"IS","mobile_code"=>"+354"],
            ["name"=>"India","code"=>"IN","mobile_code"=>"+91"],
            ["name"=>"Indonesia","code"=>"ID","mobile_code"=>"+62"],
            ["name"=>"Iran","code"=>"IR","mobile_code"=>"+98"],
            ["name"=>"Iraq","code"=>"IQ","mobile_code"=>"+964"],
            ["name"=>"Ireland","code"=>"IE","mobile_code"=>"+353"],
            ["name"=>"Israel","code"=>"IL","mobile_code"=>"+972"],
            ["name"=>"Italy","code"=>"IT","mobile_code"=>"+39"],
            ["name"=>"Jamaica","code"=>"JM","mobile_code"=>"+1-876"],
            ["name"=>"Japan","code"=>"JP","mobile_code"=>"+81"],
            ["name"=>"Jordan","code"=>"JO","mobile_code"=>"+962"],
            ["name"=>"Kazakhstan","code"=>"KZ","mobile_code"=>"+7"],
            ["name"=>"Kenya","code"=>"KE","mobile_code"=>"+254"],
            ["name"=>"Kiribati","code"=>"KI","mobile_code"=>"+686"],
            ["name"=>"Kuwait","code"=>"KW","mobile_code"=>"+965"],
            ["name"=>"Kyrgyzstan","code"=>"KG","mobile_code"=>"+996"],
            ["name"=>"Laos","code"=>"LA","mobile_code"=>"+856"],
            ["name"=>"Latvia","code"=>"LV","mobile_code"=>"+371"],
            ["name"=>"Lebanon","code"=>"LB","mobile_code"=>"+961"],
            ["name"=>"Lesotho","code"=>"LS","mobile_code"=>"+266"],
            ["name"=>"Liberia","code"=>"LR","mobile_code"=>"+231"],
            ["name"=>"Libya","code"=>"LY","mobile_code"=>"+218"],
            ["name"=>"Liechtenstein","code"=>"LI","mobile_code"=>"+423"],
            ["name"=>"Lithuania","code"=>"LT","mobile_code"=>"+370"],
            ["name"=>"Luxembourg","code"=>"LU","mobile_code"=>"+352"],
            ["name"=>"Madagascar","code"=>"MG","mobile_code"=>"+261"],
            ["name"=>"Malawi","code"=>"MW","mobile_code"=>"+265"],
            ["name"=>"Malaysia","code"=>"MY","mobile_code"=>"+60"],
            ["name"=>"Maldives","code"=>"MV","mobile_code"=>"+960"],
            ["name"=>"Mali","code"=>"ML","mobile_code"=>"+223"],
            ["name"=>"Malta","code"=>"MT","mobile_code"=>"+356"],
            ["name"=>"Marshall Islands","code"=>"MH","mobile_code"=>"+692"],
            ["name"=>"Mauritania","code"=>"MR","mobile_code"=>"+222"],
            ["name"=>"Mauritius","code"=>"MU","mobile_code"=>"+230"],
            ["name"=>"Mexico","code"=>"MX","mobile_code"=>"+52"],
            ["name"=>"Micronesia","code"=>"FM","mobile_code"=>"+691"],
            ["name"=>"Moldova","code"=>"MD","mobile_code"=>"+373"],
            ["name"=>"Monaco","code"=>"MC","mobile_code"=>"+377"],
            ["name"=>"Mongolia","code"=>"MN","mobile_code"=>"+976"],
            ["name"=>"Montenegro","code"=>"ME","mobile_code"=>"+382"],
            ["name"=>"Morocco","code"=>"MA","mobile_code"=>"+212"],
            ["name"=>"Mozambique","code"=>"MZ","mobile_code"=>"+258"],
            ["name"=>"Myanmar (Burma)","code"=>"MM","mobile_code"=>"+95"],
            ["name"=>"Namibia","code"=>"NA","mobile_code"=>"+264"],
            ["name"=>"Nauru","code"=>"NR","mobile_code"=>"+674"],
            ["name"=>"Nepal","code"=>"NP","mobile_code"=>"+977"],
            ["name"=>"Netherlands","code"=>"NL","mobile_code"=>"+31"],
            ["name"=>"New Zealand","code"=>"NZ","mobile_code"=>"+64"],
            ["name"=>"Nicaragua","code"=>"NI","mobile_code"=>"+505"],
            ["name"=>"Niger","code"=>"NE","mobile_code"=>"+227"],
            ["name"=>"Nigeria","code"=>"NG","mobile_code"=>"+234"],
            ["name"=>"North Korea","code"=>"KP","mobile_code"=>"+850"],
            ["name"=>"North Macedonia","code"=>"MK","mobile_code"=>"+389"],
            ["name"=>"Norway","code"=>"NO","mobile_code"=>"+47"],
            ["name"=>"Oman","code"=>"OM","mobile_code"=>"+968"],
            ["name"=>"Pakistan","code"=>"PK","mobile_code"=>"+92"],
            ["name"=>"Palau","code"=>"PW","mobile_code"=>"+680"],
            ["name"=>"Palestine","code"=>"PS","mobile_code"=>"+970"],
            ["name"=>"Panama","code"=>"PA","mobile_code"=>"+507"],
            ["name"=>"Papua New Guinea","code"=>"PG","mobile_code"=>"+675"],
            ["name"=>"Paraguay","code"=>"PY","mobile_code"=>"+595"],
            ["name"=>"Peru","code"=>"PE","mobile_code"=>"+51"],
            ["name"=>"Philippines","code"=>"PH","mobile_code"=>"+63"],
            ["name"=>"Poland","code"=>"PL","mobile_code"=>"+48"],
            ["name"=>"Portugal","code"=>"PT","mobile_code"=>"+351"],
            ["name"=>"Qatar","code"=>"QA","mobile_code"=>"+974"],
            ["name"=>"Romania","code"=>"RO","mobile_code"=>"+40"],
            ["name"=>"Russia","code"=>"RU","mobile_code"=>"+7"],
            ["name"=>"Rwanda","code"=>"RW","mobile_code"=>"+250"],
            ["name"=>"Saint Kitts and Nevis","code"=>"KN","mobile_code"=>"+1-869"],
            ["name"=>"Saint Lucia","code"=>"LC","mobile_code"=>"+1-758"],
            ["name"=>"Saint Vincent and the Grenadines","code"=>"VC","mobile_code"=>"+1-784"],
            ["name"=>"Samoa","code"=>"WS","mobile_code"=>"+685"],
            ["name"=>"San Marino","code"=>"SM","mobile_code"=>"+378"],
            ["name"=>"Sao Tome and Principe","code"=>"ST","mobile_code"=>"+239"],
            ["name"=>"Saudi Arabia","code"=>"SA","mobile_code"=>"+966"],
            ["name"=>"Senegal","code"=>"SN","mobile_code"=>"+221"],
            ["name"=>"Serbia","code"=>"RS","mobile_code"=>"+381"],
            ["name"=>"Seychelles","code"=>"SC","mobile_code"=>"+248"],
            ["name"=>"Sierra Leone","code"=>"SL","mobile_code"=>"+232"],
            ["name"=>"Singapore","code"=>"SG","mobile_code"=>"+65"],
            ["name"=>"Slovakia","code"=>"SK","mobile_code"=>"+421"],
            ["name"=>"Slovenia","code"=>"SI","mobile_code"=>"+386"],
            ["name"=>"Solomon Islands","code"=>"SB","mobile_code"=>"+677"],
            ["name"=>"Somalia","code"=>"SO","mobile_code"=>"+252"],
            ["name"=>"South Africa","code"=>"ZA","mobile_code"=>"+27"],
            ["name"=>"South Korea","code"=>"KR","mobile_code"=>"+82"],
            ["name"=>"South Sudan","code"=>"SS","mobile_code"=>"+211"],
            ["name"=>"Spain","code"=>"ES","mobile_code"=>"+34"],
            ["name"=>"Sri Lanka","code"=>"LK","mobile_code"=>"+94"],
            ["name"=>"Sudan","code"=>"SD","mobile_code"=>"+249"],
            ["name"=>"Suriname","code"=>"SR","mobile_code"=>"+597"],
            ["name"=>"Sweden","code"=>"SE","mobile_code"=>"+46"],
            ["name"=>"Switzerland","code"=>"CH","mobile_code"=>"+41"],
            ["name"=>"Syria","code"=>"SY","mobile_code"=>"+963"],
            ["name"=>"Taiwan","code"=>"TW","mobile_code"=>"+886"],
            ["name"=>"Tajikistan","code"=>"TJ","mobile_code"=>"+992"],
            ["name"=>"Tanzania","code"=>"TZ","mobile_code"=>"+255"],
            ["name"=>"Thailand","code"=>"TH","mobile_code"=>"+66"],
            ["name"=>"Timor-Leste","code"=>"TL","mobile_code"=>"+670"],
            ["name"=>"Togo","code"=>"TG","mobile_code"=>"+228"],
            ["name"=>"Tonga","code"=>"TO","mobile_code"=>"+676"],
            ["name"=>"Trinidad and Tobago","code"=>"TT","mobile_code"=>"+1-868"],
            ["name"=>"Tunisia","code"=>"TN","mobile_code"=>"+216"],
            ["name"=>"Turkey","code"=>"TR","mobile_code"=>"+90"],
            ["name"=>"Turkmenistan","code"=>"TM","mobile_code"=>"+993"],
            ["name"=>"Tuvalu","code"=>"TV","mobile_code"=>"+688"],
            ["name"=>"Uganda","code"=>"UG","mobile_code"=>"+256"],
            ["name"=>"Ukraine","code"=>"UA","mobile_code"=>"+380"],
            ["name"=>"United Arab Emirates","code"=>"AE","mobile_code"=>"+971"],
            ["name"=>"United Kingdom","code"=>"GB","mobile_code"=>"+44"],
            ["name"=>"United States","code"=>"US","mobile_code"=>"+1"],
            ["name"=>"Uruguay","code"=>"UY","mobile_code"=>"+598"],
            ["name"=>"Uzbekistan","code"=>"UZ","mobile_code"=>"+998"],
            ["name"=>"Vanuatu","code"=>"VU","mobile_code"=>"+678"],
            ["name"=>"Vatican City","code"=>"VA","mobile_code"=>"+379"],
            ["name"=>"Venezuela","code"=>"VE","mobile_code"=>"+58"],
            ["name"=>"Vietnam","code"=>"VN","mobile_code"=>"+84"],
            ["name"=>"Yemen","code"=>"YE","mobile_code"=>"+967"],
            ["name"=>"Zambia","code"=>"ZM","mobile_code"=>"+260"],
            ["name"=>"Zimbabwe","code"=>"ZW","mobile_code"=>"+263"],
        ];

        DB::table('countries')->insert($countries);
    }
}
